### PR TITLE
Fix/puts and dai

### LINKED ISSUE #237: RemoveLiquidity method needs to be updated
The removeLiquidity method of the UniswapConnector was changed in the latest upgrade, which I missed in the PR to bump the package version.

### PR DESCRIPTION
**Pull request by Alexangelj**
Fixes a few things, #234 #235 #236, DOES NOT FIX #237, got a little ahead of myself. Opening a new branch for that.

To do
- Formatting numbers in table/fetching data/components still a little messy, should look at cleaning up later.

### CODE REVIEW

File: app/src/state/options/hooks.tsx [hunk 1]
```diff
@@ -180,13 +185,12 @@ export const useUpdateOptions = (): ((assetName: string) => void) => {
                           Base.quantity,
                           Quote.quantity,
                           path,
-                          [reserves0, reserves1]
+                          [shortReserve, underlyingReserve]
```
Comment (zachdt) [inline app/src/state/options/hooks.tsx:188]: improvement on readability, nice

**Review by zachdt — APPROVED** [review]
